version: '3.9'
services:
  php:
    build:
      context: ./PHP
      dockerfile: Dockerfile
    command: tail -f /dev/null
  python:
    build:
      context: ./PYTHON
      dockerfile: Dockerfile
    command: tail -f /dev/null