version: "3.9"
services:
  mysql:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: library
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - mynetwork
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    networks:
      - mynetwork
    environment:
      PMA_HOST: mysql
      PMA_USER: admin
      PMA_PASSWORD: admin

volumes:
  db-data:

networks:
  mynetwork: