version: "3.9"
services:
  mysql:
    build:
      context: ./docker
      dockerfile: Dockerfile
    command: --init-file /docker-entrypoint-initdb.d/library_dump.sql
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: library
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
volumes:
  db-data: